logging:
    level:
        org:
            springframework:
                data:
                    rest:
                        core: trace
                web: trace
spring:
    profiles:
        active: @spring.profiles.active@
    data:
        rest:
            base-path: /api
    datasource:
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        
# JWT properties
habibank:
    app:
        jwtSecret = habibSecretKey
        jwtExpiration = 84600000